### ISSUE TITLE
database

### ISSUE THREAD

**Issue by sunyishen** [garanet/PyPWD#1]
hi, this app is fantastic, and may I ask how do you store names and passwords? using a database mysql?

**Comment by garanet** [comment]
Hi, thanks for your feedback, 
from the README file, you can read the "How Works" section.
```
PyPWD > Saves a DataFrame as an encrypted CVS and all passwords are encrypted too, with key and the master password.
```
So, no database but a local encrypted CVS file.
Greats

**Comment by sunyishen** [comment]
thank you
