### ISSUE TITLE
i get error

### ISSUE THREAD

**Issue by WarningDarbe** [garanet/PyPWD#2]
I created an account. I saved password. I reset password and relogin i click show password I get an erro
![error](https://user-images.githubusercontent.com/42497648/162914111-a127d796-59d7-486f-b74b-ad67d7ad492c.png)
r

**Comment by garanet** [comment]
Hi @WarningDarbe , this project is not maintained anymore, did you check/installed the right version's python and the reqs.txt libraries with the right version? https://github.com/garanet/PyPWD/blob/master/reqs.txt
